<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Termos de Uso</title>
</head>
<body>
    <h1>TERMO DE ADEQUAÇÃO À LGPD Lei Geral de Proteção de Dados Lei 13.709/2018</h1>
    <p> O presente Termo de Adequação LGPD ("Termo") tem como objeto garantir a adequação da Empresa XPTO à Lei Geral de Proteção de Dados (Lei 13.709/2018) <p>A XPTO ("Empresa"), na qualidade de Controlador(a) que corresponde a pessoa jurídica de direito público /privado, à quem compete as decisões referentes ao tratamento de dados pessoais, afirma que adota todas as medidas necessárias para assegurar a observância à Lei Geral de Proteção de Dados.</p><p> A XPTO, atua no ramo de atividade de Desenvolvimento Web, ocasião em que dados sensíveis/pessoais são coletados, sendo seu objetivo o melhor relacionamento com os seus clientes e parceiros e sempre com respeito à privacidade dos dados recepcionados.</p> <p>A Empresa se compromete a manter a confidencialidade e a integridade de todos os dados pessoais mantidos ou consultados/transmitidos eletronicamente, para garantir a proteção desses dados contra acesso não autorizado, destruição, uso, modificação, divulgação ou perda acidental ou indevida. Para fins de clareza, os dados pessoais correspondem as informações relacionadas as pessoas naturais identificadas ou identificáveis.</p> <p>A Empresa se compromete a tratar os dados pessoais a que tiver acesso somente com as respectivas permissões dos titulares desses dados, ou seja, mediante as confirmações das pessoas naturais as quais se referem os dados pessoais que serão objeto de tratamento.</p> <p>A Empresa assegura que todos os seus colaboradores prepostos, sócios, diretores, representantes ou terceiros contratados que tenham acesso aos dados pessoais que estão sob a responsabilidade da Empresa, assinaram o Termo de Confidencialidade, bem como comprometem-se a manter quaisquer Dados Pessoais estritamente confidenciais e não os utilizar para outros fins, com exceção a prestação de serviços.</p> <p>Os Dados Pessoais não poderão ser revelados a terceiros, com exceção da prévia autorização por escrito do titular dos dados pessoais, ou ainda na hipótese da Empresa, por determinação legal, ter que fornecer os dados pessoais a uma autoridade pública, ocasião em o titular dos dados pessoais que deverá ser informado previamente para que tome as medidas necessárias.</p><p>O signatário reconhece que este Termo tem plena validade em formato eletrônico, sendo equiparado a documento físico para todos os efeitos legais, reconhecendo e declarando o signatário, conforme o disposto no § 2º do artigo 10, da Medida Provisória nº 2.200-2, de 24 de agosto de 2001, que a assinatura deste Termo em meio eletrônico na plataforma RocketSign é o meio escolhido como apto a comprovar autoria e integridade do instrumento, e conferir-lhe pleno efeito legal, como se documento físico fosse.</p></p>
    
</body>
</html>